# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_pointofinterest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PointOfInterest',
            new_name='Location',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
