# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('restaurantes', '0003_auto_20170405_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('logo', models.ImageField(upload_to='restaurantes/logos')),
                ('image', models.ImageField(upload_to='restaurantes/images')),
                ('slug', models.SlugField()),
                ('abre', models.TimeField(db_index=True)),
                ('cierra', models.TimeField(db_index=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Location')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
